# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  domain_name: example.com
  secret_key_base: 87a928fd0fb27c3a564b7935fb31ac0c7492461e9ea1e4e3d0decd457acfded401106a366c27467bf2713f0708e55a3a7a3b189f80801dc95b0b4bfc018d105a

test:
  secret_key_base: f7f3fb8b62842643e079d8247195fba6c451c392508d5e39b208488786cccfc550c8e4700e41f5d34af3f368c664b090934a04a752d521002f1af0c053985e31

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
